### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by ghost** [Falkirks/MCPEDNS#3]
Why isn't it working?

**Comment by ghost** [comment]
And why is it so sliw

**Comment by falkirks** [comment]
It is so slow to load because the server runs on Heroku and goes to sleep sometimes and has to wake itself up.

**Comment by falkirks** [comment]
You will need to provide me with more information. Were you shown an error somewhere? Could you give me the name you registered so I can look it up for you?

**Comment by ghost** [comment]
Yeah my server domain is kairus.mcpe.me and the IP I registered is my IPv4 address here's the address 112.198.75.10

**Comment by falkirks** [comment]
It is registered to `192.168.254.101` currently. I have updated it to point to `112.198.75.10` because I don't allow internal IPs anyway.

**Comment by ghost** [comment]
Thanks ur cool btw
